# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'



networks:
  byfn:

services:

  sdk:
    container_name: sdk
    image: fabric-node-gm-sdk
    volumes:
        - /var/run/:/host/var/run/
        - ./config.js:/app/config.js
        - ./crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/:/app/msp/
    networks:
      - byfn
    ports:
      - 8080:80

